# Hoppy7/ArmTemplates

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: CopyFiles@2
  displayName: 'Copy Files to the Artifact Staging Directory'
  inputs:
    sourceFolder: '$(build.sourcesdirectory)'
    targetFolder: '$(build.artifactstagingdirectory)'
    contents: '**' 
    cleanTargetFolder: true
- task: PublishPipelineArtifact@0
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(build.artifactstagingdirectory)'
    artifactName: 'ArmTemplates'